
import './globals.css'
import Navbar from './components/Utilities/NavBar'
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({ subsets: ["latin"] });




export const metadata = {
  title: 'MyAnime',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${dmSans.className}, bg-color-dark`}>
      <Navbar />
      
        {children}
        </body>
    </html>
  )
}
